name: Build Amanda Binaries

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [linux, darwin, freebsd]
        arch: [amd64, arm64]

    env:
      CGO_ENABLED: 0

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'

    - name: Build for ${{ matrix.os }} / ${{ matrix.arch }}
      run: |
        go build -o "amanda_${GOOS}_${GOARCH}" ./...
      env:
        GOOS: ${{ matrix.os }}
        GOARCH: ${{ matrix.arch }}


    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: amanda_${{ matrix.os }}_${{ matrix.arch }}
        path: amanda_${{ matrix.os }}_${{ matrix.arch }}

  docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          sivel/amanda:latest
