name: Build Amanda Binaries

on:
  push:
    branches: [ main ]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip-build')"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [linux, darwin, freebsd]
        arch: [amd64, arm64]

    env:
      CGO_ENABLED: 0

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'

    - name: Build for ${{ matrix.os }} / ${{ matrix.arch }}
      run: |
        BUILD_DATE=$(date -u +%Y-%m-%dT%H:%M:%SZ)
        GO_VERSION=$(go version | awk '{print $3}')
        go build -ldflags "-X main.gitSHA=${GITHUB_SHA} -X main.buildDate=${BUILD_DATE} -X main.goVersion=${GO_VERSION}" -o "amanda_${GOOS}_${GOARCH}"
      env:
        GOOS: ${{ matrix.os }}
        GOARCH: ${{ matrix.arch }}


    - name: Upload binary artifact
      uses: actions/upload-artifact@v4
      with:
        name: amanda_${{ matrix.os }}_${{ matrix.arch }}
        path: amanda_${{ matrix.os }}_${{ matrix.arch }}

  docker:
    if: "!contains(github.event.head_commit.message, 'skip-docker')"
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: amanda_linux_*
        path: ./build
        merge-multiple: true

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          ghcr.io/${{ github.repository_owner }}/amanda:latest

  pages:
    name: Publish artifacts to pages
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create pages directory
      run: mkdir -p pages

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: pages
        merge-multiple: true

    - name: Generate index page
      run: |
        cd pages
        binary_list=""
        for file in amanda_*; do
            if [ -f "$file" ]; then
              size=$(ls -lh "$file" | awk '{print $5}')
              sha256=$(sha256sum "$file" | awk '{print $1}')
              binary_list+="        <div class=\"download-item\">
            <a href=\"$file\">$file</a>
            <span class=\"file-size\">($size)</span>
            <br><div class=\"sha256\">SHA256: $sha256</div>
        </div>
        "
            fi
        done

        sed -e "s|{{COMMIT_SHA}}|${GITHUB_SHA}|g" \
            -e "s|{{BUILD_DATE}}|$(date -u +%Y-%m-%dT%H:%M:%SZ)|g" \
            -e "s|{{REPOSITORY}}|${GITHUB_REPOSITORY}|g" \
            -e "s|{{BINARIES}}|${binary_list}|g" \
            ../.github/pages-template.html > index.html

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload to GitHub Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: pages

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
